//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promoTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogCatagory
    {
        public long id { get; set; }
        public long catalogID { get; set; }
        public int productCategoryID { get; set; }
    
        public virtual productCatalog productCatalog { get; set; }
        public virtual productCategory productCategory { get; set; }
    }
}
