//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promoTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productCatalog()
        {
            this.catalogCatagories = new HashSet<catalogCatagory>();
        }
    
        public long catalogID { get; set; }
        public int supplierID { get; set; }
        public string thumbImageURL { get; set; }
        public string productTitle { get; set; }
        public bool isPremeum { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public bool isOffer { get; set; }
        public string pdfURL { get; set; }
        public string seo_metaKeyword { get; set; }
        public string seo_OGImage { get; set; }
        public string seo_OGDesription { get; set; }
        public string seo_OGTitle { get; set; }
        public string offerProviderURl { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> offerExpireDate { get; set; }
        public string slugURL { get; set; }
        public string pdfName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogCatagory> catalogCatagories { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
