//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promoTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.productCatalogs = new HashSet<productCatalog>();
        }
    
        public int supplierID { get; set; }
        public string supplierName { get; set; }
        public string City { get; set; }
        public Nullable<int> StateID { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<int> SupplierFor { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productCatalog> productCatalogs { get; set; }
        public virtual state state { get; set; }
    }
}
