//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promoTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customOrder
    {
        public int orderID { get; set; }
        public string name { get; set; }
        public string companyName { get; set; }
        public string comments { get; set; }
        public string email { get; set; }
        public bool isActive { get; set; }
        public string other1 { get; set; }
        public string other2 { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<int> catalogID { get; set; }
        public string phone { get; set; }
        public string companyURl { get; set; }
        public string logo { get; set; }
    }
}
