//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace promoTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class technology
    {
        public long technologyID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string seo_metaKeyword { get; set; }
        public string seo_OGImage { get; set; }
        public string seo_OGDesription { get; set; }
        public string seo_OGTitle { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string shortDescription { get; set; }
        public string slugURL { get; set; }
    }
}
